/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package serped;

import java.awt.Component;
import java.awt.Font;
import java.awt.PopupMenu;
import java.io.IOException;
import java.io.Writer;
import java.net.MalformedURLException;
import java.net.ProtocolException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.xml.parsers.ParserConfigurationException;
import javax.xml.xpath.XPathExpressionException;
import org.xml.sax.SAXException;

/**
 *
 * @author malen
 */
public class Ventana2 extends javax.swing.JFrame {

    private ConsumirXML recurso;
    private ArrayList listaAgnos;
    private ArrayList listaLugares;
    private String lugar;
    private String grado;
    private String genero;
    private String agno;
    private ArrayList opcionesSel;
    /**
     * Creates new form Ventana2
     */
    public Ventana2() {
        initComponents();
        try {
            this.recurso = new ConsumirXML();
            agnadirAgnos();
            agnadirLugar();
            agnadirGenero();
            agnadirGrado();
            this.jTextPane1.disable();
            
        } catch (ProtocolException ex) {
            Logger.getLogger(Ventana2.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Ventana2.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParserConfigurationException ex) {
            Logger.getLogger(Ventana2.class.getName()).log(Level.SEVERE, null, ex);
        } catch (XPathExpressionException ex) {
            Logger.getLogger(Ventana2.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SAXException ex) {
            Logger.getLogger(Ventana2.class.getName()).log(Level.SEVERE, null, ex);
        }
        setTitle("Serped - Consultas");
        setIconImage(new ImageIcon(getClass().getResource("/icono/portapapeles.png")).getImage());
        setResizable(false);
        setVisible(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bVolverV2 = new javax.swing.JButton();
        bBuscar1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        mensajeU = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        bVolverV2.setBackground(new java.awt.Color(255, 255, 255));
        bVolverV2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        bVolverV2.setText("Volver");
        bVolverV2.setName(""); // NOI18N
        bVolverV2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverVentana1(evt);
            }
        });
        jPanel1.add(bVolverV2);
        bVolverV2.setBounds(120, 310, 100, 30);
        bVolverV2.getAccessibleContext().setAccessibleName("bBuscar");

        bBuscar1.setBackground(new java.awt.Color(255, 255, 255));
        bBuscar1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        bBuscar1.setLabel("Buscar");
        bBuscar1.setName(""); // NOI18N
        bBuscar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBuscar1realizarConsulta(evt);
            }
        });
        jPanel1.add(bBuscar1);
        bBuscar1.setBounds(120, 260, 100, 30);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Indefinido" }));
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(210, 140, 110, 22);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Indefinido" }));
        jPanel1.add(jComboBox2);
        jComboBox2.setBounds(210, 180, 110, 22);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Indefinido" }));
        jPanel1.add(jComboBox3);
        jComboBox3.setBounds(210, 220, 110, 22);

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Indefinido" }));
        jPanel1.add(jComboBox4);
        jComboBox4.setBounds(210, 90, 110, 22);

        jTextPane1.setBackground(new java.awt.Color(204, 204, 204));
        jScrollPane2.setViewportView(jTextPane1);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(460, 0, 200, 350);

        mensajeU.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(mensajeU);
        mensajeU.setBounds(250, 290, 200, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Grado");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(80, 220, 80, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Lugar");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(80, 130, 60, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Año");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(80, 90, 41, 16);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Consultas");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(120, 20, 520, 40);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Género");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(80, 180, 80, 20);

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icono/fondo.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 691, 414);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 690, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bBuscar1realizarConsulta(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBuscar1realizarConsulta
        this.jTextPane1.enable();
        this.opcionesSel=new ArrayList<String>();
        if(this.jComboBox1.getSelectedItem().equals("Indefinido")||this.jComboBox2.getSelectedItem().equals("Indefinido")||this.jComboBox3.getSelectedItem().equals("Indefinido")){
            this.mensajeU.setFont(new Font("Serif",Font.BOLD,14));
            
            this.mensajeU.setText("Rellena los datos del formulario");
        }else{
            this.mensajeU.setText("");
            this.lugar=(String) this.jComboBox1.getSelectedItem();
            this.agno=(String) this.jComboBox4.getSelectedItem();
            this.genero=(String) this.jComboBox2.getSelectedItem();
            this.grado=(String)this.jComboBox3.getSelectedItem();
            this.opcionesSel.add(this.agno);
            this.opcionesSel.add(this.lugar);
            this.opcionesSel.add(this.genero);
            this.opcionesSel.add(this.grado);
        escribirResultado(this.recurso.buscarConsulta(this.opcionesSel));
        }
    }//GEN-LAST:event_bBuscar1realizarConsulta

    private void volverVentana1(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverVentana1
        setVisible(false);
        Ventana1 ventanaIn=new Ventana1();
    }//GEN-LAST:event_volverVentana1

   public void agnadirAgnos() throws IOException, MalformedURLException, ParserConfigurationException, XPathExpressionException, SAXException{
       this.listaAgnos=this.recurso.getItemsAgno();
       for(int i=0;i<listaAgnos.size();i++){
           this.jComboBox4.addItem((String)this.listaAgnos.get(i));
       }
       
   }
   
   public void agnadirLugar(){
       this.listaLugares=this.recurso.getItemsLugar();
       for(int i=0;i<this.listaLugares.size();i++){
           this.jComboBox1.addItem((String) this.listaLugares.get(i));
       }
   }
   
   public void agnadirGenero(){
       this.jComboBox2.addItem("Masculino");
       this.jComboBox2.addItem("Femenino");
   }
   
   public void agnadirGrado(){
       this.jComboBox3.addItem("1");
       this.jComboBox3.addItem("2");
       this.jComboBox3.addItem("3");
       
   }
   
   public void escribirResultado(ArrayList<String>resultadoPantalla){
       
       this.jTextPane1.setText("");
       String frase="\n\n\n\n\n     Año: "+resultadoPantalla.get(0)+"\n\n     Localización: "+resultadoPantalla.get(1)+"\n\n     "+resultadoPantalla.get(2)+" Grado "+resultadoPantalla.get(3)+": \n     "+resultadoPantalla.get(4)+"\n\n     TOTAL: "+resultadoPantalla.get(5)+" personas";
       Font fuentePantalla=new Font("Serif",Font.BOLD,14);
       jTextPane1.setFont(fuentePantalla);
       this.jTextPane1.setText(frase);
   }
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bBuscar1;
    private javax.swing.JButton bVolverV2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JLabel mensajeU;
    // End of variables declaration//GEN-END:variables
}
