/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package serped;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.ProtocolException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.xml.parsers.ParserConfigurationException;
import javax.xml.xpath.XPathExpressionException;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.category.DefaultCategoryDataset;
import org.xml.sax.SAXException;

/**
 *
 * @author malen
 */
public class Ventana4Gra extends javax.swing.JFrame {

    private String lugar1;
    private String lugar2;
    private String agno1;
    private String agno2;
    private ConsumirXML consultaG;
    private ArrayList listaAgnos;
    private ArrayList listaLugares;
    private ArrayList[]imprimir;
    private int contadorD;
    private DefaultCategoryDataset dcd;

    public Ventana4Gra() throws MalformedURLException, XPathExpressionException {
        dcd=new DefaultCategoryDataset();
        initComponents();
        imprimir=new ArrayList[12];
        this.contadorD=0;
        this.jPanel2.setVisible(false);
        try {
            this.consultaG=new ConsumirXML();
            agnadirAgnos();
            agnadirLugar();
        } catch (ProtocolException ex) {
            Logger.getLogger(Ventana4Gra.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Ventana4Gra.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParserConfigurationException ex) {
            Logger.getLogger(Ventana4Gra.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SAXException ex) {
            Logger.getLogger(Ventana4Gra.class.getName()).log(Level.SEVERE, null, ex);
        }
        setTitle("Serped - Comparación gráfica");
        setIconImage(new ImageIcon(getClass().getResource("/icono/portapapeles.png")).getImage());
        setResizable(false);
        setVisible(true);
        
    }

    public void agnadirAgnos() throws IOException, MalformedURLException, ParserConfigurationException, XPathExpressionException, SAXException{
       this.listaAgnos=this.consultaG.getItemsAgno();
       for(int i=0;i<listaAgnos.size();i++){
           this.jComboBox2.addItem((String)this.listaAgnos.get(i));
           this.jComboBox4.addItem((String)this.listaAgnos.get(i));
       }
    }

    public void agnadirLugar(){
       this.listaLugares=this.consultaG.getItemsLugar();
       for(int i=0;i<this.listaLugares.size();i++){
           this.jComboBox1.addItem((String) this.listaLugares.get(i));
           this.jComboBox3.addItem((String) this.listaLugares.get(i));
       }
   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        bGraficos = new javax.swing.JButton();
        jComboBox4 = new javax.swing.JComboBox<>();
        bVolverv3 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        mensajeU = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jPanel2.setFocusable(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1110, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(30, 80, 1110, 580);

        bGraficos.setBackground(new java.awt.Color(255, 255, 255));
        bGraficos.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        bGraficos.setText("Gráficos");
        bGraficos.setToolTipText("");
        bGraficos.setName(""); // NOI18N
        bGraficos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generarGra(evt);
            }
        });
        jPanel1.add(bGraficos);
        bGraficos.setBounds(1270, 450, 100, 30);

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Indefinido" }));
        jPanel1.add(jComboBox4);
        jComboBox4.setBounds(1340, 370, 110, 22);

        bVolverv3.setBackground(new java.awt.Color(255, 255, 255));
        bVolverv3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        bVolverv3.setText("Volver");
        bVolverv3.setName(""); // NOI18N
        bVolverv3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVolverv3volverVentana1(evt);
            }
        });
        jPanel1.add(bVolverv3);
        bVolverv3.setBounds(1270, 520, 100, 30);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Indefinido" }));
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(1340, 210, 110, 22);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Indefinido" }));
        jPanel1.add(jComboBox3);
        jComboBox3.setBounds(1340, 320, 110, 22);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Indefinido" }));
        jPanel1.add(jComboBox2);
        jComboBox2.setBounds(1340, 270, 110, 22);

        mensajeU.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        mensajeU.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(mensajeU);
        mensajeU.setBounds(1160, 596, 330, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Año");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(1200, 370, 70, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Lugar 1");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(1200, 210, 70, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Lugar 2");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(1200, 320, 70, 20);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Comparación Gráfica");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(1190, 80, 520, 40);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Año");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(1200, 270, 80, 20);

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icono/fondo.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(-10, -90, 1520, 790);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1509, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 692, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bVolverv3volverVentana1(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVolverv3volverVentana1
        setVisible(false);
        Ventana1 ventanaIn=new Ventana1();
    }//GEN-LAST:event_bVolverv3volverVentana1

    private void generarGra(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generarGra
        if(this.jComboBox1.getSelectedItem().toString().equals("Indefinido")||this.jComboBox2.getSelectedItem().toString().equals("Indefinido")||this.jComboBox3.getSelectedItem().toString().equals("Indefinido")||this.jComboBox4.getSelectedItem().toString().equals("Indefinido")){
            this.mensajeU.setText("Rellena todos los campos del formulario.");
        }else{
            this.mensajeU.setText("");
        this.jPanel2.setVisible(false);
        //Guardo los datos del usuario.
        this.lugar1=this.jComboBox1.getSelectedItem().toString();
        this.lugar2=this.jComboBox3.getSelectedItem().toString();
        this.agno1=this.jComboBox2.getSelectedItem().toString();
        this.agno2=this.jComboBox4.getSelectedItem().toString();
        try {
            buscarInfoG();
        } catch (IOException ex) {
            Logger.getLogger(Ventana4Gra.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParserConfigurationException ex) {
            Logger.getLogger(Ventana4Gra.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SAXException ex) {
            Logger.getLogger(Ventana4Gra.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    }//GEN-LAST:event_generarGra

    
    private void buscarInfoG() throws ProtocolException, IOException, MalformedURLException, ParserConfigurationException, SAXException{
        this.consultaG=new ConsumirXML();
        int numeroDatos=0;
        ArrayList<String>datosCg=new ArrayList<String>();
        int contador2=0;
        int contador=1;
        for(int j=0;j<2;j++){
        for(int i=0;i<6;i++){
            if(j==0){
                datosCg.add(this.agno1);
                datosCg.add(this.lugar1);
            }else{
                datosCg.add(this.agno2);
                datosCg.add(this.lugar2);
            }
            if(contador==1){
            datosCg.add("Masculino");
            
            }else{
                datosCg.add("Femenino");
                
            }
            datosCg.add(String.valueOf(contador2+1));
            guardaResultados(this.consultaG.buscarConsulta(datosCg),numeroDatos);
            datosCg.clear();
            numeroDatos++;
            contador2++;
            if(i==2){
                contador2=0;
                contador=2;
            }
            
        }
        contador2=0;
        contador=1;
        }
         
        imprimeGrafico();
    }
    
    public void imprimeGrafico(){
        
        //Vacío la instancia de la clase DefaultCategoryDataset.
        dcd.clear();
        
        //Defino los datos.
        for(int i=0;i<12;i++){
            dcd.setValue(Integer.parseInt(this.imprimir[i].get(4).toString()),this.imprimir[i].get(1).toString()+" Año "+this.imprimir[i].get(0).toString(),this.imprimir[i].get(2).toString()+" "+this.imprimir[i].get(3).toString());
        }
        
      
        
        //Instancio la clase FreeChart.
        JFreeChart grafico=ChartFactory.createBarChart("SERPED", "Servicio Personas Con Dependencia",  "nº Personas", dcd);
        //Creo el panel donde se muestra.
        ChartPanel panelG=new ChartPanel(grafico);
        panelG.setMouseWheelEnabled(false);
        panelG.setPreferredSize(new Dimension(500,400));
        this.jPanel2.setLayout(new BorderLayout());
        this.jPanel2.add(panelG,BorderLayout.CENTER);
        this.jPanel2.setVisible(true);
        
    }
    
    public void guardaResultados(ArrayList<String>datos,int numero){
            this.imprimir[numero]=datos;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bGraficos;
    private javax.swing.JButton bVolverv3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel mensajeU;
    // End of variables declaration//GEN-END:variables
}
