/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package serped;

import com.itextpdf.text.DocumentException;
import java.awt.Font;
import java.awt.PopupMenu;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.ProtocolException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.xml.parsers.ParserConfigurationException;
import javax.xml.xpath.XPathExpressionException;
import org.xml.sax.SAXException;

/**
 *
 * @author malen
 */
public class Ventana3Inf extends javax.swing.JFrame {

    private int plantilla;
    private ConsumirXML xmlInf;
    private ArrayList lugaresIn;
    private ConsumirXML conXML;
    private String tituloArchivo;
    private String[][]datosInforme;
    private String tipoArchivo;
    
    public Ventana3Inf() throws ProtocolException, IOException, MalformedURLException, ParserConfigurationException, SAXException {
        
        //Creo una instancia de la clase ConsumirXML.
        this.xmlInf=new ConsumirXML();
        
        initComponents();
        this.jComboBox2.disable();
        this.plantilla=1;
        pintaPlantilla(this.plantilla);
        agnadeLug();
        this.conXML=new ConsumirXML();
        setResizable(false);
        setIconImage(new ImageIcon(getClass().getResource("/icono/portapapeles.png")).getImage());
        setTitle("Serped - Informes");
        setVisible(true);
    }
    
    //Añado los lugares al input para seleccionar.
    public void agnadeLug(){
        this.lugaresIn=new ArrayList<String>();
        this.lugaresIn=this.xmlInf.getItemsLugar();
        for(int i=0;i<this.lugaresIn.size();i++){
            this.jComboBox3.addItem((String)this.lugaresIn.get(i));
        }
    }
    
    //Pinto la plantilla en pantalla.
    public void pintaPlantilla(int numeroP){
        if(!this.jComboBox1.getSelectedItem().toString().equals("TXT")){
        this.jTextPane1.setFont(new Font("Serif",Font.BOLD,14));
        if(numeroP==1){
            this.jTextPane1.setText("                    Título"+"\n\n\nLocalización\nCódigo\n\nAño\n\n               Texto párrafo1\n\nAño\n\n               Texto párrafo 2");
        }else{
            this.jTextPane1.setText("                    Título"+"\n\n\nLocalización\n\n               Texto párrafo1\n                     Año\n\n\n               Texto párrafo2\n                     Año");
        }
        }else{
            this.jTextPane1.setText("");
        }
    }
    
    public void cerrarVentana3(){
        setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bBuscar = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        bVolverv3 = new javax.swing.JButton();
        jComboBox3 = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jTextField1 = new javax.swing.JTextField();
        mensajeU = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        bBuscar.setBackground(new java.awt.Color(255, 255, 255));
        bBuscar.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        bBuscar.setText("Generar");
        bBuscar.setToolTipText("");
        bBuscar.setName(""); // NOI18N
        bBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generarArchivo(evt);
            }
        });
        jPanel1.add(bBuscar);
        bBuscar.setBounds(130, 250, 100, 30);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TXT", "PDF" }));
        jComboBox1.setToolTipText("");
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cambioF(evt);
            }
        });
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(210, 120, 110, 22);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2" }));
        jComboBox2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cambioP(evt);
            }
        });
        jPanel1.add(jComboBox2);
        jComboBox2.setBounds(210, 160, 110, 22);

        bVolverv3.setBackground(new java.awt.Color(255, 255, 255));
        bVolverv3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        bVolverv3.setText("Volver");
        bVolverv3.setName(""); // NOI18N
        bVolverv3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVolverv3volverVentana1(evt);
            }
        });
        jPanel1.add(bVolverv3);
        bVolverv3.setBounds(130, 300, 100, 30);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Indefinido" }));
        jPanel1.add(jComboBox3);
        jComboBox3.setBounds(210, 80, 110, 22);

        jTextPane1.setBackground(new java.awt.Color(204, 204, 204));
        jScrollPane2.setViewportView(jTextPane1);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(460, 0, 200, 350);

        jTextField1.setToolTipText("");
        jPanel1.add(jTextField1);
        jTextField1.setBounds(210, 200, 110, 22);

        mensajeU.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(mensajeU);
        mensajeU.setBounds(240, 270, 210, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Lugar");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(80, 80, 70, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Formato");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(80, 120, 80, 22);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Título");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(80, 200, 70, 20);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Informes");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(120, 20, 520, 40);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Plantilla");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(80, 160, 80, 20);

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icono/fondo.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 691, 414);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 690, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bVolverv3volverVentana1(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVolverv3volverVentana1
        setVisible(false);
        Ventana1 ventanaIn=new Ventana1();
    }//GEN-LAST:event_bVolverv3volverVentana1

    private void generarArchivo(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generarArchivo

        if(this.jComboBox3.getSelectedItem().toString().equals("Indefinido")||this.jTextField1.getText().equals("")){
            this.mensajeU.setFont(new Font("Serif",Font.BOLD,14));
            this.mensajeU.setText("Rellena el formulario completo.");
        }else{
            this.mensajeU.setText("");
        ArrayList<String>listaDatos=new ArrayList<String>();
        try {
            //Consulto los datos del lugar seleccionado.
            this.datosInforme=this.conXML.datosEs(this.jComboBox3.getSelectedItem().toString());
            
            //Guardo el título del archivo.
            this.tituloArchivo=this.jTextField1.getText();
            //Guardo el formato del archivo.
            this.tipoArchivo=this.jComboBox1.getSelectedItem().toString();
            PlantillaInf archivo=new PlantillaInf(Integer.parseInt(jComboBox2.getSelectedItem().toString()),this.tituloArchivo,this.tipoArchivo,this.datosInforme);
            //Genero el archivo.
            if(archivo.generarPDF()){
                this.mensajeU.setFont(new Font("Serif",Font.BOLD,14));
                this.mensajeU.setText("Archivo generado correctamente");
            }
        
            
        } catch (IOException ex) {
            Logger.getLogger(Ventana3Inf.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParserConfigurationException ex) {
            Logger.getLogger(Ventana3Inf.class.getName()).log(Level.SEVERE, null, ex);
        } catch (XPathExpressionException ex) {
            Logger.getLogger(Ventana3Inf.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SAXException ex) {
            Logger.getLogger(Ventana3Inf.class.getName()).log(Level.SEVERE, null, ex);
        } catch (DocumentException ex) {
            Logger.getLogger(Ventana3Inf.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
       
    }//GEN-LAST:event_generarArchivo

    private void cambioP(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cambioP
        this.plantilla=Integer.parseInt(jComboBox2.getSelectedItem().toString());
        pintaPlantilla(this.plantilla);
    }//GEN-LAST:event_cambioP

    private void cambioF(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cambioF
                                 
        if(this.jComboBox1.getSelectedItem().toString().equals("TXT")){
            pintaPlantilla(this.plantilla);
            this.jComboBox2.disable();
        }else{
            pintaPlantilla(this.plantilla);
            this.jComboBox2.enable();
        }
        
           
    }//GEN-LAST:event_cambioF

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bBuscar;
    private javax.swing.JButton bVolverv3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JLabel mensajeU;
    // End of variables declaration//GEN-END:variables
}

